function generateInbox(){

var randomEvents = `Number	Event
1	A sexual scandal involving your candidate appears on the news. A former employee states that he had sexual relations with your candidate while she worked on his campaign. This will influence a lot of voters with a ferm belief system based on family values and from the highly religious groups. Bad, bad president!
2	A data collection agency just announced (unofficially, of course) that they have put together a data base with the behavioural patterns of all american citizens. It costs a huge chunk of your money, but it would be highly valuable to get your hands on such an important piece of information. Would you like to acquire said data base?
3	A terrorist organization has threatened to attack two major cities of the US. Asked on his oppinion about the threat, your candidate stated that the current president should take immediate action and bomb the living hell out of the entire country. Bad move. This created a huge uproar amongst the citizens and people are questioning your candidate's ability to lead a country and his diplomacy skills. Your candidates popularity amongst the people concerned with the external affairs and national security will be influenced.
4	In a live interview with CNN, your candidate was asked about his oppinion on the increasing unemployment rates in the US. His answer was not a favourable one (it never is!). He stated that most unemployed people are immagrants anyway, so they might just get discouraged enough by this to move back to their country. Naturally, your candidates statement will influence the voters who militate to create more jobs in the US and most of the immigrants now dislike him.
5	Your candidate just tweeted something like "Climate changes is just a hoax meant to generate some cash to a few very influential and wealthy people. Don't believe everything you hear, people. The dinasaurs didn't have cars and a blooming industry and they still turned into ice cubes. #realtalk". Needless to say that his ratings amonst the voters preocuppied with the environment will be influenced.
6	During a meet&greet session held in Arkansas, your candidate was asked what his oppinion about the healthcare system would be. A couple of unfavourable words and it all went downhill from there. The general impression your candidate made was he wouldn't really know what he was talking about. Needless to say, this will influence the people who are very concerned about the healthcare system in the US.
7	While having a private discussion with one of his political advisors, your candidate has been filmed stating something extremely sexist in regards to women's rights and gender equality. It was taken out of context and uploaded on youtube, which generated a lot of fuss on the internet, upgrading the video to "viral" in under 24 hours. The popularity amongst female voters will be influenced.
8	Your candidate has just been seen playing catch in a park with a random kid. They seem to have a lot of fun. It's a PR gold mine! Your candidates popularity amongst the people who regard family values as highly important will be influenced by that.
9	It's SuperBowl Sunday. Everyone is hyped! The game is about to begin, but first the national anthem kicks off. Your candidate was just caught shedding some tears while the national anthem was playing. This impressed everyone and it spread instantly around the internet. Your candidates popularity amongst the voters who are more nationalist is influenced.
10	A night out, attending a social event, your candidate was asked about some racial stereotypes that are still an issue in the US. He reffered to caucasian males as being "normal" and any ethnicity as being "brown", "yellow" and so on, which caused an entire uproar amongst the people attending the event. This racial slip influences your candidates popularity amongst the voters concerned with the racial issues.
11	Accepting the invitation your candidate received from greenpeace to plant some trees has proven to be a great decision. The popularity amongst the environmentally-concerned voters has been influenced.
12	A famous vlogger just died this week due to a drug overdose. Asked about his oppinion on the matter, your candidate stated that drugs should be illegal and it shouldn't be possible to get your hands so easy on drugs. This statement has been applauded by the voters and his popularity has been influenced, especially amongst those who are fighting wars on drugs.
13	On your candidates pressure and constant harassment of the current president, a war hero has been awarded the purple heart. It's all due to your candidates consistency and perseverance. This act has not gone unnoticed and your candidates popularity is influenced amongst the voters fond of the military.
14	In an interview given to a scientific publication, your candidate was asked about his plan of budget allocation to the research field. His answer, that research is not what this country needs right now, was obviously not received as too positive. His rating amongst the science passionate voters was influenced.
15	A debate of your candidate with one of the highest ranking lawyers in the US has sparked some conflict. Some poorly chosen phrasing has led the general public to believe your candidate has no clue about the legal system, which, in turns leads to the popularity of your candidate in the eyes of voters that are very passionate about the American justice system being influenced.`.split('\n').slice(1); var randomEventsObj = {1: randomEvents, 2: randomEvents};
var weeklyEmails = `Week	Kanye	Rock		
1	So, have we won? Then move your ass and do your job! Jeez, man, at least TRY to be a little bit more like me.	Welcome, champ! Let's hit the gym and start working on this campaign right after!		
2	Yo! What's the word from last week? Are we looking good? I know I am, but how are you looking?	Oh, I didn't see you there. I was busy doing some deadlifts. So, give me some good news!		
3	Gotta take my queen to the Bahamas this week. She deserves a little bit of rest, she's kinda stressed with me becoming president and all this. So do not call, text, tweet or whatever me. I won't answer. You're on your own, Boring Prime!	Have you seen my protein shake? I swear I've been looking for that heavenly deliciousness all over the place.		
4	This week we'll be focusing on destroying that "boulder" guy. What? What's his name? Ah, right. The rock. Yeah, let's transform him into sand.	Who is this guy who's running against me? Kayne West? Never heard of her.		
5	Just got off the phone with Jay-Z. What's all this stuff people are talking about my tweets? "Ridiculous" they call them. These mere mortals can't even understand when a God addresses them.	Let's hit the gym! No pressing matters for now. Politics is just like powerlifting: once you get the weight off the ground, you're pretty much good to go.		
6	What's our agenda for this week? Can we kill this Rocky dude now?	We're about half way through. We got this! And remember: there's no "i" in "champions"!		
7	Look at this new Gucci sash I bought. Look at it. Look at it very closely. See what this sash is made out of? It's made out of class. Something you'll never have.	New week, 7 new reasons to hit the gym!		
8	Some asshole just tweeted about Kim she would look like a hobbit. Can I expel people from the US when I'm president? Imma expel his ass to a different continent! Like Canada or Alaska!	I'm getting pretty annoyed by that Kanye guy. He is nothing. Nothing! I mean, does he even lift?!		
9	Yo! I just found out each man can only be president for a 4 year mandate. And this can happened twice in a lifetime. What?! I'll only be president 8 years? This is unconstitutional!	Once I'm elected president, my first ruling will be to make gym attendance mandatory. I see too much weakness in the gym. Too much!		
10	I'm Yeezy! Artist, God, fashion icon, husband of a Goddess, producer and secret cricket enthusiast. Remind me again, who are you?	I've had such a great week, champ! I've managed to benchpress the equivalent of a really, really fat cow.		
11	Explain to me why I just got kicked out of the White House! What is this?! I'm the president of the United States of America! What is all this shit about me not being president yet?	How are we doing? Are we winning or are we winning? See what I did there? I've left no room for losing. Losing is for losers.		
12	I still don't understand how this presidenting works. Am I president yet?	God, I'm buffed! It's getting harder and harder to find clothes that won't explode whenever I flex my bicep. Aweeeesooooome!		
13	What happens if I take, say, 2 months off from being a president? Like, I want to take Kim and North to Africa for hunting, who can I elect as president substitution?	What a lovely day to hit the gym! Just a little bit more and we're in the White House. Push through the pain, champ!		
14	What's a debate and why do I receive phone calls from random morons trying to make me confirm my participation?	I'm so ready for this debate. If this little, feeble man will attack, insult or make me feel uncomfortable in any way, I swear I will double-suplex his ass!		
15	Okay, so NOW it's official. Now I'm president. THIS is the last week before the election?…oh, man! Being president requires so much patience! That's why we haven't had a decent president yet. But don't worry, Yeezy got this!	Easiest campaign of my life! I don't know why we need to wait for the final results, we already feel like champions. Isn't that right, CHAMP?		`.split('\n').slice(1);

randomEventsObj = {1: randomEvents, 2: randomEvents}; 

function pickRandomEvent(candidateFlag, evArr) {var r = evArr[Math.floor(Math.random()*evArr.length)].split('\t')[1]; var ind = evArr.indexOf(r); randomEventsObj[candidateFlag].splice(ind, 1); return r;}; candidates[1]['inbox'] = Array(15).fill(0).map(function(e, i){return [pickRandomEvent(1, randomEventsObj[1]), weeklyEmails[i].split('\t')[1]]}); 

var randomEvents2 = `Number	Event
1	A sexual scandal involving your candidate appears on the news. A former employee states that he had sexual relations with your candidate while she worked on his campaign. This will influence a lot of voters with a ferm belief system based on family values and from the highly religious groups. Bad, bad president!
2	A data collection agency just announced (unofficially, of course) that they have put together a data base with the behavioural patterns of all american citizens. It costs a huge chunk of your money, but it would be highly valuable to get your hands on such an important piece of information. Would you like to acquire said data base?
3	A terrorist organization has threatened to attack two major cities of the US. Asked on his oppinion about the threat, your candidate stated that the current president should take immediate action and bomb the living hell out of the entire country. Bad move. This created a huge uproar amongst the citizens and people are questioning your candidate's ability to lead a country and his diplomacy skills. Your candidates popularity amongst the people concerned with the external affairs and national security will be influenced.
4	In a live interview with CNN, your candidate was asked about his oppinion on the increasing unemployment rates in the US. His answer was not a favourable one (it never is!). He stated that most unemployed people are immagrants anyway, so they might just get discouraged enough by this to move back to their country. Naturally, your candidates statement will influence the voters who militate to create more jobs in the US and most of the immigrants now dislike him.
5	Your candidate just tweeted something like "Climate changes is just a hoax meant to generate some cash to a few very influential and wealthy people. Don't believe everything you hear, people. The dinasaurs didn't have cars and a blooming industry and they still turned into ice cubes. #realtalk". Needless to say that his ratings amonst the voters preocuppied with the environment will be influenced.
6	During a meet&greet session held in Arkansas, your candidate was asked what his oppinion about the healthcare system would be. A couple of unfavourable words and it all went downhill from there. The general impression your candidate made was he wouldn't really know what he was talking about. Needless to say, this will influence the people who are very concerned about the healthcare system in the US.
7	While having a private discussion with one of his political advisors, your candidate has been filmed stating something extremely sexist in regards to women's rights and gender equality. It was taken out of context and uploaded on youtube, which generated a lot of fuss on the internet, upgrading the video to "viral" in under 24 hours. The popularity amongst female voters will be influenced.
8	Your candidate has just been seen playing catch in a park with a random kid. They seem to have a lot of fun. It's a PR gold mine! Your candidates popularity amongst the people who regard family values as highly important will be influenced by that.
9	It's SuperBowl Sunday. Everyone is hyped! The game is about to begin, but first the national anthem kicks off. Your candidate was just caught shedding some tears while the national anthem was playing. This impressed everyone and it spread instantly around the internet. Your candidates popularity amongst the voters who are more nationalist is influenced.
10	A night out, attending a social event, your candidate was asked about some racial stereotypes that are still an issue in the US. He reffered to caucasian males as being "normal" and any ethnicity as being "brown", "yellow" and so on, which caused an entire uproar amongst the people attending the event. This racial slip influences your candidates popularity amongst the voters concerned with the racial issues.
11	Accepting the invitation your candidate received from greenpeace to plant some trees has proven to be a great decision. The popularity amongst the environmentally-concerned voters has been influenced.
12	A famous vlogger just died this week due to a drug overdose. Asked about his oppinion on the matter, your candidate stated that drugs should be illegal and it shouldn't be possible to get your hands so easy on drugs. This statement has been applauded by the voters and his popularity has been influenced, especially amongst those who are fighting wars on drugs.
13	On your candidates pressure and constant harassment of the current president, a war hero has been awarded the purple heart. It's all due to your candidates consistency and perseverance. This act has not gone unnoticed and your candidates popularity is influenced amongst the voters fond of the military.
14	In an interview given to a scientific publication, your candidate was asked about his plan of budget allocation to the research field. His answer, that research is not what this country needs right now, was obviously not received as too positive. His rating amongst the science passionate voters was influenced.
15	A debate of your candidate with one of the highest ranking lawyers in the US has sparked some conflict. Some poorly chosen phrasing has led the general public to believe your candidate has no clue about the legal system, which, in turns leads to the popularity of your candidate in the eyes of voters that are very passionate about the American justice system being influenced.`.split('\n').slice(1);

 var randomEventsObj2 = {1: randomEvents2, 2: randomEvents2}; candidates[2]['inbox'] = Array(15).fill(0).map(function(e, i){return [pickRandomEvent(2, randomEventsObj2[2]), weeklyEmails[i].split('\t')[2]]});
 
}