var texts = `Topics	Kanye West	The Rock	Non-candidate related																						
Game introduction	Option A. The republican party led by the magnificent Kanye West	Option B. The democrat party led by the strong Dwayne "the Rock" Johnson	It is the year 2020. After a first round that has already been regarded as the most unconventional first round of presidential elections of the past 100 years, only two candidates made it to the second round.  Would you like to run the republican party and help Kanye West go to the White House, or would you like to run the democrat party and help Dwayne "the Rock" Johnson move into the White House? Choose wisely.																						
Intro text for the candidate chosen by the player	Of course you chose me. Who else would you have chosen? I am God's vessel! My only regret in life is that I have never seen myself perform live. Such a treat for everyone… Anywho, why are you staying there idle, worshipping me? Get to work! I need a new team and won't waste my precious time on such boring tasks, that's your job. You'll be in charge of everything that's boring. Cool? Cool. I don't care what your name is, I'll call you "Boring Prime". Okay, Boring Prime, now put that team together to get me to that White House. I'll make it the Kanye House. Here's $xxxxx. Spend them at will, it's entirely your responsibilty who you hire and fire, just know the seating is limited, so don't go paying people willy-nilly with my hard earned fortuine, this stuff won't fly around here. You can hire 8 people. That's it. I'll mail you the list of options you have for each position. Choose wisely. If I lose because of the team you've put together, Boring Prime, there will be consequences. Just ask the former Boring Prime. Hah! Just kidding, you won't find him. Ever. He....disappeared. Good luck!	Hey there, sport! Welcome to the winning team. You have made the right choice. What's your name? You know what, it doesn't matter. I'll just call you "Champion". That is what you are. You are a champion. So, Champ, let me break it down to you: I'll give you $xxxxx to put in place a team of winners. The slots are limited, though. We have 8 open positions that need to be filled with the greatest talent you find on the market. It's up to you how you use this money, who you hire and who you fire. I won't intervene, that's your job. My job will be to be awesome. In public. Make the great people of the USA vote for me. I might need to turn a trick or two, put the charms on, but I got this, don't worry. What I need you to do is run my campaign and take care of all matters. We got this! We're champions!																							
Poll increase reaction	So Yeezy. See what I did there? Don't worry, you won't get it anyway.	Yeah, Champ! We're doing this! WE ARE CHAMPIONS!																							
Poll decrease reaction	How can something like that happen to a GOD?! There must be an error.	Uh-oh. What's happening? We need to work harder.																							`;

var textsObj = {};

var textsArr = texts.split('\n');

textsObj['intro-text'] = textsArr[1].split('\t')[3];

