var weeklyEmails = `Week	Kanye	Rock		
1	So, have we won? Then move your ass and do your job! Jeez, man, at least TRY to be a little bit more like me.	Welcome, champ! Let's hit the gym and start working on this campaign right after!		
2	Yo! What's the word from last week? Are we looking good? I know I am, but how are you looking?	Oh, I didn't see you there. I was busy doing some deadlifts. So, give me some good news!		
3	Gotta take my queen to the Bahamas this week. She deserves a little bit of rest, she's kinda stressed with me becoming president and all this. So do not call, text, tweet or whatever me. I won't answer. You're on your own, Boring Prime!	Have you seen my protein shake? I swear I've been looking for that heavenly deliciousness all over the place.		
4	This week we'll be focusing on destroying that "boulder" guy. What? What's his name? Ah, right. The rock. Yeah, let's transform him into sand.	Who is this guy who's running against me? Kayne West? Never heard of her.		
5	Just got off the phone with Jay-Z. What's all this stuff people are talking about my tweets? "Ridiculous" they call them. These mere mortals can't even understand when a God addresses them.	Let's hit the gym! No pressing matters for now. Politics is just like powerlifting: once you get the weight off the ground, you're pretty much good to go.		
6	What's our agenda for this week? Can we kill this Rocky dude now?	We're about half way through. We got this! And remember: there's no "i" in "champions"!		
7	Look at this new Gucci sash I bought. Look at it. Look at it very closely. See what this sash is made out of? It's made out of class. Something you'll never have.	New week, 7 new reasons to hit the gym!		
8	Some asshole just tweeted about Kim she would look like a hobbit. Can I expel people from the US when I'm president? Imma expel his ass to a different continent! Like Canada or Alaska!	I'm getting pretty annoyed by that Kanye guy. He is nothing. Nothing! I mean, does he even lift?!		
9	Yo! I just found out each man can only be president for a 4 year mandate. And this can happened twice in a lifetime. What?! I'll only be president 8 years? This is unconstitutional!	Once I'm elected president, my first ruling will be to make gym attendance mandatory. I see too much weakness in the gym. Too much!		
10	I'm Yeezy! Artist, God, fashion icon, husband of a Goddess, producer and secret cricket enthusiast. Remind me again, who are you?	I've had such a great week, champ! I've managed to benchpress the equivalent of a really, really fat cow.		
11	Explain to me why I just got kicked out of the White House! What is this?! I'm the president of the United States of America! What is all this shit about me not being president yet?	How are we doing? Are we winning or are we winning? See what I did there? I've left no room for losing. Losing is for losers.		
12	I still don't understand how this presidenting works. Am I president yet?	God, I'm buffed! It's getting harder and harder to find clothes that won't explode whenever I flex my bicep. Aweeeesooooome!		
13	What happens if I take, say, 2 months off from being a president? Like, I want to take Kim and North to Africa for hunting, who can I elect as president substitution?	What a lovely day to hit the gym! Just a little bit more and we're in the White House. Push through the pain, champ!		
14	What's a debate and why do I receive phone calls from random morons trying to make me confirm my participation?	I'm so ready for this debate. If this little, feeble man will attack, insult or make me feel uncomfortable in any way, I swear I will double-suplex his ass!		
15	Okay, so NOW it's official. Now I'm president. THIS is the last week before the election?…oh, man! Being president requires so much patience! That's why we haven't had a decent president yet. But don't worry, Yeezy got this!	Easiest campaign of my life! I don't know why we need to wait for the final results, we already feel like champions. Isn't that right, CHAMP?		`.split('\n');

